on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN || github.token }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install keymap-drawer
        run: pip install "keymap-drawer<0.20"
      
      - name: Create output directories
        run: |
          mkdir -p keymap-drawer
          mkdir -p images
      
      - name: Parse ZMK keymap
        run: python -m keymap_drawer parse -c 12 -z config/sofle.keymap > keymap-drawer/sofle.yaml
      
      - name: Generate QWERTY layer image
        run: python -m keymap_drawer draw keymap-drawer/sofle.yaml --select-layers "QWERTY" -o images/qwerty_layer.svg
          
      - name: Generate LOWER layer image
        run: python -m keymap_drawer draw keymap-drawer/sofle.yaml --select-layers "LOWER" -o images/lower_layer.svg
          
      - name: Generate RAISE layer image
        run: python -m keymap_drawer draw keymap-drawer/sofle.yaml --select-layers "RAISE" -o images/raise_layer.svg
          

      - name: Generate ADJUST layer image
        run: python -m keymap_drawer draw keymap-drawer/sofle.yaml --select-layers "ADJUST" -o images/adjust_layer.svg
      
      - name: Upload layer images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: keymap-images
          path: images/*.svg
            
      - name: Commit and push images (on main branch only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add keymap-drawer/sofle.yaml images/*.svg
          git diff --staged --quiet || git commit -m "[keymap-drawer] Update keymap images"
          git push